### ISSUE TITLE
The download links got 404

### ISSUE THREAD

**Issue by KngStr** [ImageMagick/WizardsToolkit#2]
Hi,

I want to download this toolkit to check for digest of ImageMagick.
But all of the download links can not be accessed in this url :`https://urban-warrior.org/WizardsToolkit/script/download.php`

Thanks.

**Comment by urban-warrior** [comment]
The checksums for ImageMagick adhere to industry standards, allowing you to employ any tool, such as `sha256sum`, for generating a checksum. This can be compared against the checksum generated using the WizardsToolkit utility, `digest`.
